apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgresql
data:
  # property-like keys; each key maps to a simple value
  DB_HOST: "10.100.39.103"
  DB_PORT: "5432"
  DB_USERNAME: myuser
  DB_NAME: mydatabase